#cloud-config

package_update: true

packages:
  - apache2
  - php
  - libapache2-mod-php
  - php-mysql
  - php-curl
  - php-gd
  - php-mbstring
  - php-xml
  - php-xmlrpc
  - php-soap
  - php-intl
  - php-zip
  - certbot
  - python3-certbot-apache
  - wget

runcmd:
  - wget -O /tmp/wordpress.tar.gz https://wordpress.org/latest.tar.gz
  - tar -xzvf /tmp/wordpress.tar.gz -C /var/www
  - chown -R www-data:www-data /var/www/wordpress
  - wget -O /etc/apache2/sites-available/wordpress.conf ./wordpress.conf
  - a2dissite 000-default
  - a2ensite wordpress.conf
  - systemctl enable apache2
  - systemctl restart apache2
  - certbot -n --apache --agree-tos --redirect --hsts --uir --staple-ocsp -d jonathan-courtois-dev.fr -v

final_message: "The system is finally up, after $UPTIME seconds"
